spring:
  application:
    name: liquibase-project-poc
  datasource:
    url: jdbc:mysql://localhost:3306/liquibasedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

